// frontend/src/app/components/queue/queue.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-queue',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './queue.component.html'
})
export class QueueComponent {
  @Input() queue: any[] = [];
  @Input() currentVideo: any = null;

  @Output() playSong = new EventEmitter<number>();
  @Output() removeSong = new EventEmitter<number>();
}

<div class="queue-container">
  <div class="current-playing" *ngIf="currentVideo">
    <h3>Now Playing</h3>
    <div class="queue-item active">
      <img [src]="currentVideo.snippet.thumbnails.default.url" alt="thumbnail" />
      <div class="queue-item-info">
        <div class="queue-item-title">{{ currentVideo.snippet.title }}</div>
        <div class="queue-item-channel">{{ currentVideo.snippet.channelTitle }}</div>
      </div>
    </div>
  </div>

  <h3 style="margin-top: 1rem; margin-bottom: 0.5rem; color: var(--text-muted); font-size: 0.9rem; text-transform: uppercase; letter-spacing: 1px;">Up Next</h3>
  
  <div class="queue-list" *ngIf="queue.length > 0; else emptyQueue">
    <div class="queue-item" *ngFor="let video of queue; let i = index">
      <div class="queue-item-number">{{ i + 1 }}</div>
      <img [src]="video.snippet.thumbnails.default.url" alt="thumbnail" />
      <div class="queue-item-info">
        <div class="queue-item-title">{{ video.snippet.title }}</div>
        <div class="queue-item-channel">{{ video.snippet.channelTitle }}</div>
      </div>
      <div class="queue-item-actions">
        <button class="btn btn-icon" (click)="playSong.emit(i)" title="Play Now">▶</button>
        <button class="btn btn-icon" (click)="removeSong.emit(i)" title="Remove">✕</button>
      </div>
    </div>
  </div>

  <ng-template #emptyQueue>
    <div class="empty-queue">
      The queue is empty. Search for a song to start singing!
    </div>
  </ng-template>
</div>

// frontend/src/components/Queue.jsx
import React from 'react';
import { Play, X } from 'lucide-react';

export default function Queue({ queue, currentVideo, onPlaySong, onRemoveSong }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%', overflow: 'hidden' }}>
      <div className="queue-header">
        <span>QUEUE</span>
        {queue.length > 0 && <span className="queue-badge">{queue.length}</span>}
      </div>

      <div className="queue-list">
        {currentVideo && (
          <div className="queue-item" style={{ background: '#f8fafc' }}>
            <img src={currentVideo.snippet.thumbnails.default.url} alt="thumb" className="queue-thumb" />
            <div className="queue-details">
              <div className="queue-meta">
                <Play size={10} fill="var(--primary)" color="var(--primary)" />
                <span style={{ color: 'var(--primary)' }}>NOW PLAYING</span>
              </div>
              <div className="queue-title">{currentVideo.snippet.title}</div>
            </div>
          </div>
        )}

        {queue.length === 0 && !currentVideo && (
          <div style={{ padding: '1rem', textAlign: 'center', color: 'var(--text-muted)', fontSize: '0.8rem' }}>
            Queue is empty.
          </div>
        )}

        {queue.map((video, index) => (
          <div key={`${video.id.videoId}-${index}`} className="queue-item">
            <img src={video.snippet.thumbnails.default.url} alt="thumb" className="queue-thumb" />
            
            <div className="queue-details">
              <div className="queue-meta">
                <span style={{ color: 'var(--text-muted)' }}>UNSTARTED</span>
              </div>
              <div className="queue-title">{video.snippet.title}</div>
            </div>
            
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
              <button className="btn" style={{ padding: '0.25rem', color: 'var(--success)' }} onClick={() => onPlaySong(index)}>
                <Play size={14} />
              </button>
              <button className="btn" style={{ padding: '0.25rem', color: 'var(--danger)' }} onClick={() => onRemoveSong(index)}>
                <X size={14} />
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
