// frontend/src/components/SongSearch.jsx
import React, { useState, useRef, useEffect } from 'react';
import { Search } from 'lucide-react';

const API_KEY = import.meta.env.VITE_YOUTUBE_API_KEY;

export default function SongSearch({ onAddSong }) {
  const [query, setQuery] = useState('');
  const [results, setResults] = useState([]);
  const [loading, setLoading] = useState(false);
  const dropdownRef = useRef(null);

  useEffect(() => {
    const handleClickOutside = (event) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target)) {
        setResults([]);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, [dropdownRef]);

  const searchSongs = async (e) => {
    e.preventDefault();
    if (!query) return;
    
    setLoading(true);
    const searchQuery = query.toLowerCase().includes('karaoke') ? query : query + ' karaoke';
    
    try {
      const res = await fetch(`https://www.googleapis.com/youtube/v3/search?part=snippet&q=${encodeURIComponent(searchQuery)}&maxResults=10&type=video&videoEmbeddable=true&key=${API_KEY}`);
      const data = await res.json();
      
      if (data.items) {
        setResults(data.items);
      }
    } catch (err) {
      console.error('Error fetching songs:', err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ position: 'relative', flex: 1 }} ref={dropdownRef}>
      <form onSubmit={searchSongs} className="search-input-group">
        <button type="button" className="btn" style={{ background: 'transparent', color: 'var(--text-muted)' }}>
          <Search size={16} />
        </button>
        <input 
          type="text" 
          placeholder="Search" 
          value={query}
          onChange={(e) => setQuery(e.target.value)}
        />
        <button type="submit" className="btn btn-search" disabled={loading}>
          {loading ? '...' : 'Search'}
        </button>
      </form>

      {results.length > 0 && (
        <div className="search-results-dropdown">
          {results.map((video) => (
            <div key={video.id.videoId} className="queue-item" style={{ cursor: 'pointer' }} onClick={() => {
              onAddSong(video);
              setResults([]);
              setQuery('');
            }}>
              <img src={video.snippet.thumbnails.default.url} alt="thumbnail" className="queue-thumb" />
              <div className="queue-details">
                <div className="queue-title">{video.snippet.title}</div>
                <div className="queue-meta">
                  <span style={{ color: 'var(--text-muted)' }}>{video.snippet.channelTitle}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// frontend/src/app/components/song-search/song-search.component.ts
import { Component, EventEmitter, Output, ViewChild, ElementRef, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { AppConfigService } from '../../app-config.service';
import { LucideSearch } from '@lucide/angular';

@Component({
  selector: 'app-song-search',
  standalone: true,
  imports: [CommonModule, FormsModule, LucideSearch],
  templateUrl: './song-search.component.html',
  host: {
    'style': 'display: block; position: relative; flex: 1;'
  }
})
export class SongSearchComponent {
  @Output() addSong = new EventEmitter<any>();
  @ViewChild('dropdown') dropdownRef!: ElementRef;

  query = '';
  results: any[] = [];
  isSearching = false;
  showDropdown = false;

  constructor(private http: HttpClient, private configService: AppConfigService) {}

  async handleSearch(e?: Event) {
    if (e) {
      e.preventDefault();
    }
    if (!this.query.trim()) return;

    this.isSearching = true;
    this.showDropdown = true;
    
    try {
      const backendUrl = this.configService.backendUrl || '';
      const url = `${backendUrl}/api/youtube/search?q=${encodeURIComponent(this.query + ' karaoke')}`;
      
      const data = await this.http.get<any>(url).toPromise();
      if (data && data.items) {
        this.results = data.items.filter((item: any) => item.id.videoId);
      }
    } catch (err) {
      console.error('Error fetching songs:', err);
    } finally {
      this.isSearching = false;
    }
  }

  selectSong(video: any) {
    this.addSong.emit(video);
    this.showDropdown = false;
    this.query = '';
  }

  @HostListener('document:mousedown', ['$event'])
  onGlobalClick(event: MouseEvent) {
    if (this.dropdownRef && !this.dropdownRef.nativeElement.contains(event.target)) {
      this.showDropdown = false;
    }
  }
}

<div class="search-container" #dropdown>
  <form (submit)="handleSearch($event)" style="display: flex; gap: 0.5rem; width: 100%;">
    <input 
      type="text" 
      [(ngModel)]="query" 
      name="query"
      class="search-input" 
      placeholder="Search for a song..."
      autocomplete="off"
      (focus)="results.length > 0 && (showDropdown = true)"
    />
    <button type="submit" class="btn btn-primary" [disabled]="isSearching">
      <ng-container *ngIf="isSearching; else searchIcon">...</ng-container>
      <ng-template #searchIcon>
        <lucide-icon [name]="SearchIcon" [size]="20"></lucide-icon>
      </ng-template>
    </button>
  </form>

  <div class="search-dropdown" *ngIf="showDropdown && results.length > 0">
    <div 
      *ngFor="let video of results"
      class="search-result-item"
      (click)="selectSong(video)"
    >
      <img [src]="video.snippet.thumbnails.default.url" alt="thumbnail" />
      <div class="search-result-info">
        <div class="search-result-title">{{ video.snippet.title }}</div>
        <div class="search-result-channel">{{ video.snippet.channelTitle }}</div>
      </div>
    </div>
  </div>
</div>
