// frontend/src/app/app.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { io, Socket } from 'socket.io-client';
import { AppConfigService } from './app-config.service';

import { LucideAngularModule, Mic, LayoutGrid, Play, Power, Search } from 'lucide-angular';
import { YoutubePlayerComponent } from './components/youtube-player/youtube-player.component';
import { SongSearchComponent } from './components/song-search/song-search.component';
import { QueueComponent } from './components/queue/queue.component';
import { PitchDetectorComponent } from './components/pitch-detector/pitch-detector.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule, 
    LucideAngularModule, 
    YoutubePlayerComponent, 
    SongSearchComponent, 
    QueueComponent, 
    PitchDetectorComponent
  ],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit, OnDestroy {
  visitorId = '';
  isRemote = false;
  private socket: Socket | null = null;

  queue: any[] = [];
  currentVideo: any = null;

  readonly MicIcon = Mic;
  readonly LayoutGridIcon = LayoutGrid;
  readonly PlayIcon = Play;
  readonly PowerIcon = Power;
  readonly SearchIcon = Search;

  constructor(private configService: AppConfigService) {}

  ngOnInit() {
    const urlParams = new URLSearchParams(window.location.search);
    const remoteId = urlParams.get('remote');

    if (remoteId) {
      this.isRemote = true;
      this.visitorId = remoteId;
    } else {
      let vid = localStorage.getItem('visitorID');
      if (!vid) {
        vid = Math.random().toString(36).substring(2, 10);
        localStorage.setItem('visitorID', vid);
      }
      this.visitorId = vid;
    }

    const backendUrl = this.configService.backendUrl || '';
    this.socket = io(backendUrl || '/');

    this.socket.on('connect', () => {
      this.socket?.emit('joinRoom', this.visitorId);
    });

    this.socket.on('syncState', (state: any) => {
      this.queue = state.queue || [];
      this.currentVideo = state.currentVideo || null;
    });

    if (remoteId) {
      this.socket.emit('requestSync', this.visitorId);
    }

    this.requestWakeLock();
    document.addEventListener('visibilitychange', () => {
      if (document.visibilityState === 'visible') {
        this.requestWakeLock();
      }
    });
  }

  ngOnDestroy() {
    if (this.socket) {
      this.socket.close();
    }
  }

  private async requestWakeLock() {
    try {
      if ('wakeLock' in navigator) {
        await (navigator as any).wakeLock.request('screen');
      }
    } catch (err) {}
  }

  private syncToRoom(newQueue: any[], newCurrent: any) {
    if (this.socket) {
      this.socket.emit('updateState', {
        roomId: this.visitorId,
        queue: newQueue,
        currentVideo: newCurrent
      });
    }
  }

  handleAddSong(video: any) {
    const newQueue = [...this.queue, video];
    this.queue = newQueue;
    this.syncToRoom(newQueue, this.currentVideo);

    if (!this.currentVideo && !this.isRemote) {
      this.playNext(newQueue);
    }
  }

  handleRemoveSong(index: number) {
    const newQueue = this.queue.filter((_, i) => i !== index);
    this.queue = newQueue;
    this.syncToRoom(newQueue, this.currentVideo);
  }

  handlePlaySong(index: number) {
    const video = this.queue[index];
    const newQueue = this.queue.filter((_, i) => i !== index);
    this.currentVideo = video;
    this.queue = newQueue;
    this.syncToRoom(newQueue, video);
  }

  playNext(currentQueue = this.queue) {
    if (currentQueue.length > 0) {
      const nextVideo = currentQueue[0];
      const newQueue = currentQueue.slice(1);
      this.currentVideo = nextVideo;
      this.queue = newQueue;
      this.syncToRoom(newQueue, nextVideo);
    } else {
      this.currentVideo = null;
      this.syncToRoom([], null);
    }
  }
}

<ng-container *ngIf="isRemote; else mainApp">
  <div style="padding: 1rem; display: flex; flex-direction: column; gap: 1rem;">
    <h2 style="text-align: center; font-weight: 800;">
      <span class="logo-blue">Yoona</span><span class="logo-red">Sing</span> Remote
    </h2>
    <app-song-search (addSong)="handleAddSong($event)"></app-song-search>
    <app-queue 
      [queue]="queue" 
      [currentVideo]="currentVideo"
      (playSong)="handlePlaySong($event)"
      (removeSong)="handleRemoveSong($event)">
    </app-queue>
  </div>
</ng-container>

<ng-template #mainApp>
  <header class="app-header">
    <div class="logo-container">
      <lucide-icon [name]="MicIcon" color="#ef4444" [size]="24"></lucide-icon>
      <span><span class="logo-blue">Yoona</span><span class="logo-red">Sing</span></span>
    </div>
    <div style="display: flex; gap: 1rem; color: var(--text-muted);">
      <lucide-icon [name]="SearchIcon" [size]="20"></lucide-icon>
      <lucide-icon [name]="LayoutGridIcon" [size]="20"></lucide-icon>
    </div>
  </header>

  <div class="main-content">
    <div class="video-section">
      <app-youtube-player 
        [videoId]="currentVideo?.id?.videoId" 
        (end)="playNext()">
      </app-youtube-player>
      <app-pitch-detector [isPlaying]="!!currentVideo && !isRemote"></app-pitch-detector>
    </div>
    
    <div class="sidebar-section panel">
      <div class="controls-row">
        <app-song-search (addSong)="handleAddSong($event)"></app-song-search>
        <button class="btn btn-icon btn-success">
          <lucide-icon [name]="PlayIcon" [size]="16" color="white"></lucide-icon>
        </button>
        <button class="btn btn-icon btn-danger">
          <lucide-icon [name]="PowerIcon" [size]="16"></lucide-icon>
        </button>
      </div>
      
      <app-queue 
        [queue]="queue" 
        [currentVideo]="currentVideo"
        (playSong)="handlePlaySong($event)"
        (removeSong)="handleRemoveSong($event)">
      </app-queue>
    </div>
  </div>

  <div class="chatbot-bubble">
    Can't decide on a song? Let me help!
  </div>
  <div class="chatbot-icon">
    🎵
  </div>
</ng-template>

// frontend/src/App.jsx
import React, { useState, useEffect } from 'react';
import { io } from 'socket.io-client';
import { Mic, LayoutGrid, Play, Power, Search } from 'lucide-react';
import YouTubePlayer from './components/YouTubePlayer';
import SongSearch from './components/SongSearch';
import Queue from './components/Queue';
import PitchDetector from './components/PitchDetector';

const BACKEND_URL = import.meta.env.VITE_BACKEND_URL || 'http://localhost:4000';

function App() {
  const [visitorId, setVisitorId] = useState('');
  const [isRemote, setIsRemote] = useState(false);
  const [socket, setSocket] = useState(null);
  
  const [queue, setQueue] = useState([]);
  const [currentVideo, setCurrentVideo] = useState(null);

  useEffect(() => {
    const urlParams = new URLSearchParams(window.location.search);
    const remoteId = urlParams.get('remote');
    
    let vid;
    if (remoteId) {
      setIsRemote(true);
      vid = remoteId;
    } else {
      vid = localStorage.getItem('visitorID') || Math.random().toString(36).substring(2, 10);
      localStorage.setItem('visitorID', vid);
    }
    setVisitorId(vid);

    const newSocket = io(BACKEND_URL);
    setSocket(newSocket);

    newSocket.on('connect', () => {
      newSocket.emit('joinRoom', vid);
    });

    newSocket.on('syncState', (state) => {
      setQueue(state.queue || []);
      setCurrentVideo(state.currentVideo || null);
    });

    if (remoteId) {
      newSocket.emit('requestSync', vid);
    }

    return () => newSocket.close();
  }, []);

  const syncToRoom = (newQueue, newCurrent) => {
    if (socket) {
      socket.emit('updateState', {
        roomId: visitorId,
        queue: newQueue,
        currentVideo: newCurrent
      });
    }
  };

  const handleAddSong = (video) => {
    const newQueue = [...queue, video];
    setQueue(newQueue);
    syncToRoom(newQueue, currentVideo);
    
    if (!currentVideo && !isRemote) {
      playNext(newQueue);
    }
  };

  const handleRemoveSong = (index) => {
    const newQueue = queue.filter((_, i) => i !== index);
    setQueue(newQueue);
    syncToRoom(newQueue, currentVideo);
  };

  const handlePlaySong = (index) => {
    const video = queue[index];
    const newQueue = queue.filter((_, i) => i !== index);
    setCurrentVideo(video);
    setQueue(newQueue);
    syncToRoom(newQueue, video);
  };

  const playNext = (currentQueue = queue) => {
    if (currentQueue.length > 0) {
      const nextVideo = currentQueue[0];
      const newQueue = currentQueue.slice(1);
      setCurrentVideo(nextVideo);
      setQueue(newQueue);
      syncToRoom(newQueue, nextVideo);
    } else {
      setCurrentVideo(null);
      syncToRoom([], null);
    }
  };

  useEffect(() => {
    let wakeLock = null;
    const requestWakeLock = async () => {
      try {
        if ('wakeLock' in navigator) {
          wakeLock = await navigator.wakeLock.request('screen');
        }
      } catch (err) {}
    };
    requestWakeLock();
    document.addEventListener('visibilitychange', () => {
      if (wakeLock !== null && document.visibilityState === 'visible') {
        requestWakeLock();
      }
    });
  }, []);

  if (isRemote) {
    return (
      <div style={{ padding: '1rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
        <h2 style={{ textAlign: 'center', fontWeight: '800' }}><span className="logo-blue">Yoona</span><span className="logo-red">Sing</span> Remote</h2>
        <SongSearch onAddSong={handleAddSong} />
        <Queue 
          queue={queue} 
          currentVideo={currentVideo}
          onPlaySong={handlePlaySong}
          onRemoveSong={handleRemoveSong}
        />
      </div>
    );
  }

  return (
    <>
      <header className="app-header">
        <div className="logo-container">
          <Mic color="#ef4444" size={24} />
          <span><span className="logo-blue">Yoona</span><span className="logo-red">Sing</span></span>
        </div>
        <div style={{ display: 'flex', gap: '1rem', color: 'var(--text-muted)' }}>
          <Search size={20} />
          <LayoutGrid size={20} />
        </div>
      </header>

      <div className="main-content">
        <div className="video-section">
          <YouTubePlayer 
            videoId={currentVideo?.id?.videoId} 
            onEnd={() => playNext()}
          />
          <PitchDetector isPlaying={!!currentVideo && !isRemote} />
        </div>
        
        <div className="sidebar-section panel">
          <div className="controls-row">
            <SongSearch onAddSong={handleAddSong} />
            <button className="btn btn-icon btn-success"><Play size={16} fill="white" /></button>
            <button className="btn btn-icon btn-danger"><Power size={16} /></button>
          </div>
          
          <Queue 
            queue={queue} 
            currentVideo={currentVideo}
            onPlaySong={handlePlaySong}
            onRemoveSong={handleRemoveSong}
          />
        </div>
      </div>

      <div className="chatbot-bubble">
        Can't decide on a song? Let me help!
      </div>
      <div className="chatbot-icon">
        🎵
      </div>
    </>
  );
}

export default App;
